"""Fetch satellite imagery tiles and stitch into a single ground texture for the flight simulator.

Usage:
    python tools/fetch_ground_map.py --lat 42.6977 --lon 23.3219 --zoom 14 --tiles 16 --label sofia

Defaults to Sofia, Bulgaria. Use --lat, --lon to change city. Examples:
    New York City: --lat 40.7484 --lon -73.9857
    London:        --lat 51.5074 --lon -0.1278
    Tokyo:         --lat 35.6895 --lon 139.6917

Source: Esri World Imagery (https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9)
Free for non-commercial use with attribution. Tiles are 256x256.

Output:
    flightSimulator/assets/ground-map.jpg          (stitched JPEG, ~3-5MB at 4096x4096)
    flightSimulator/src/ground-map-data.ts         (base64-embedded for the Power BI sandbox)
"""

from __future__ import annotations

import argparse
import math
import sys
import time
import base64
import urllib.request
from io import BytesIO
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow required: pip install Pillow")

TILE_URL = "https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"
TILE_SIZE = 256
USER_AGENT = "FlightSimGroundMapFetcher/1.0 (Power BI custom visual demo)"

REPO_ROOT = Path(__file__).resolve().parent.parent
ASSETS_DIR = REPO_ROOT / "assets"
SRC_DIR = REPO_ROOT / "src"


def lonlat_to_tile(lon: float, lat: float, zoom: int) -> tuple[float, float]:
    """Convert lon/lat to fractional tile coords (slippy map / Web Mercator)."""
    n = 2 ** zoom
    x = (lon + 180.0) / 360.0 * n
    lat_rad = math.radians(lat)
    y = (1.0 - math.log(math.tan(lat_rad) + 1 / math.cos(lat_rad)) / math.pi) / 2.0 * n
    return x, y


def fetch_tile(z: int, x: int, y: int, retries: int = 3) -> Image.Image:
    url = TILE_URL.format(z=z, x=x, y=y)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            with urllib.request.urlopen(req, timeout=15) as resp:
                return Image.open(BytesIO(resp.read())).convert("RGB")
        except Exception as e:
            last_err = e
            time.sleep(0.5 * (attempt + 1))
    raise RuntimeError(f"Tile {z}/{x}/{y} failed after {retries} attempts: {last_err}")


def build_mosaic(lat: float, lon: float, zoom: int, grid: int, workers: int = 8) -> Image.Image:
    """Download a grid x grid block of tiles centred on (lat, lon) and stitch them."""
    center_x, center_y = lonlat_to_tile(lon, lat, zoom)
    half = grid // 2
    tx_start = int(center_x) - half
    ty_start = int(center_y) - half
    n = 2 ** zoom
    if tx_start < 0 or ty_start < 0 or tx_start + grid > n or ty_start + grid > n:
        raise ValueError(f"Tile range out of bounds at zoom {zoom} for grid={grid}")

    size = grid * TILE_SIZE
    mosaic = Image.new("RGB", (size, size))
    total = grid * grid
    done = 0
    failures: list[str] = []

    print(f"Fetching {total} tiles ({grid}x{grid}) at zoom {zoom} centred on ({lat}, {lon})...")

    def task(ix: int, iy: int):
        return ix, iy, fetch_tile(zoom, tx_start + ix, ty_start + iy)

    with ThreadPoolExecutor(max_workers=workers) as pool:
        futures = [pool.submit(task, ix, iy) for ix in range(grid) for iy in range(grid)]
        for fut in as_completed(futures):
            try:
                ix, iy, tile = fut.result()
                mosaic.paste(tile, (ix * TILE_SIZE, iy * TILE_SIZE))
                done += 1
                if done % 16 == 0 or done == total:
                    print(f"  {done}/{total}")
            except Exception as e:
                failures.append(str(e))

    if failures:
        print(f"WARNING: {len(failures)} tile(s) failed:", *failures[:5], sep="\n  ")

    return mosaic


def write_ts_module(jpg_bytes: bytes, ts_path: Path, label: str) -> None:
    b64 = base64.b64encode(jpg_bytes).decode("ascii")
    header = (
        "// Auto-generated by tools/fetch_ground_map.py - do not edit by hand.\n"
        f"// Source: Esri World Imagery, label={label}.\n"
        f"// Image size: {len(jpg_bytes)} bytes JPEG, base64 length: {len(b64)} chars.\n"
    )
    body = f'export const GROUND_MAP_BASE64 = "data:image/jpeg;base64,{b64}";\n'
    ts_path.write_text(header + body, encoding="utf-8")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--lat", type=float, default=42.6977, help="Centre latitude (default: Sofia 42.6977)")
    p.add_argument("--lon", type=float, default=23.3219, help="Centre longitude (default: Sofia 23.3219)")
    p.add_argument("--zoom", type=int, default=14, help="Tile zoom (default 14, ~9.5m/px)")
    p.add_argument("--tiles", type=int, default=16, help="Grid size in tiles (default 16 = 4096x4096 image)")
    p.add_argument("--quality", type=int, default=85, help="JPEG quality (default 85)")
    p.add_argument("--workers", type=int, default=8, help="Parallel HTTP workers")
    p.add_argument("--label", type=str, default="sofia", help="Label for the TS file header")
    p.add_argument("--no-ts", action="store_true", help="Skip writing the .ts file (PNG/JPG only)")
    args = p.parse_args(argv)

    ASSETS_DIR.mkdir(parents=True, exist_ok=True)
    SRC_DIR.mkdir(parents=True, exist_ok=True)

    mosaic = build_mosaic(args.lat, args.lon, args.zoom, args.tiles, args.workers)

    jpg_path = ASSETS_DIR / "ground-map.jpg"
    buf = BytesIO()
    mosaic.save(buf, format="JPEG", quality=args.quality, optimize=True, progressive=True)
    jpg_bytes = buf.getvalue()
    jpg_path.write_bytes(jpg_bytes)
    print(f"Wrote {jpg_path} ({len(jpg_bytes):,} bytes)")

    if not args.no_ts:
        ts_path = SRC_DIR / "ground-map-data.ts"
        write_ts_module(jpg_bytes, ts_path, args.label)
        print(f"Wrote {ts_path} ({ts_path.stat().st_size:,} bytes)")

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
